Add EventDestination Actions Schema in lib-dmtf
ODIM-Project/ODIM pull request #1063
Opened 2023-01-10 13:10 UTC by mohamed-shahid-afrid

Actions for every resource vary, Adding Actions schema for EventDestination resources

2023-01-10 18:00 UTC, chauberahul1993 approved these changes

2023-01-11 03:24 UTC, hemkapoor approved these changes

2023-01-11 03:29 UTC, amar-shalgar requested changes
Why only EventDestination actions are added. where are all other schema models?

2023-01-11 04:25 UTC, amar-shalgar approved these changes

2023-01-11 08:10 UTC, merged