Implement tasks for volume create functionality
ODIM-Project/ODIM pull request #1120
Opened 2023-02-15 10:09 UTC by hemkapoor

Implement tasks for volume create functionality

2023-02-15 10:44 UTC, sriteja-sabbineni approved these changes

2023-02-15 11:07 UTC, chauberahul1993 approved these changes

2023-02-21 06:54 UTC, amar-shalgar requested changes

2023-02-21 09:27 UTC, hemkapoor commented on svc-systems/systems/storage.go
> +	var targetURI = "/redfish/v1/Systems/" + req.SystemID + "/Storage/" + req.StorageInstance + "/Volumes"
No Amar, we dont get URI in the proto request. We get systemID and storage id, using these value we generate URI.
Below are the values which we get it request:
      SessionToken         string   
	SystemID             string  
	StorageInstance      string   
	VolumeID             string  
	RequestBody          []byte

2023-02-21 10:22 UTC, amar-shalgar approved these changes

2023-02-21 10:22 UTC, merged