Issue 328 - addressed a comment "remove unnecessary ` `"
ODIM-Project/ODIM pull request #340
Opened 2021-01-25 09:17 UTC by chinmayic

Removed from $ sudo systemctl enable docker.

2021-01-25 09:31 UTC, shivacharanms approved these changes

2021-01-27 16:31 UTC, Bharath-KKB approved these changes

2021-01-27 16:32 UTC, Bharath-KKB requested changes
update lables and project

2021-02-16 15:55 UTC, Bharath-KKB approved these changes

2021-03-02 13:44 UTC, ehsjoar approved these changes

2021-03-30 12:02 UTC, merged