Issue 345 - addressed readme doc
ODIM-Project/ODIM pull request #348
Opened 2021-01-27 10:01 UTC by chinmayic

Addressed the following comment:

"The current README.md talks about ODIMRA, which is not a known thing in the community. It also mentions GRF without introducing the acronym. Finally, we should introduce what ODIM is before we dive into how to install it. The reason for a high priority here is that there is an upcoming release and we need it fixed before that release."

Added ODIMRA introduction and logical architecture diagram.

2021-01-27 16:33 UTC, Bharath-KKB requested changes
Add lables, project before we merge.

2021-01-28 14:46 UTC, ehsjoar requested changes
I like the introduction. This looks good
Unfortunately it is also now clear that we have a couple of other issues going on that needs to be addressed:

- Following the README.md the build fails due to some issues with URP
- The README.md refers to older versions of docker-ce (18.03.1~ce~3-0~ubuntu) that is not compliant with the docker-ce-cli that is in Ubuntu's repository for 18.04.5 (latest 18 LTS)

I think we need to address all this in the README file so new developers and community users can get a clean build.

2021-01-29 06:28 UTC, chinmayic commented
The following issue is addressed in the latest readme that has been merged:

The README.md refers to older versions of docker-ce (18.03.1ce3-0~ubuntu) that is not compliant with the docker-ce-cli that is in Ubuntu's repository for 18.04.5 (latest 18 LTS)

2021-02-16 15:54 UTC, Bharath-KKB approved these changes

2021-03-03 13:40 UTC, ehsjoar approved these changes

2021-03-30 12:04 UTC, shivacharanms approved these changes

2021-03-30 17:37 UTC, merged