Documentation
ODIM-Project/ODIM pull request #35
Opened 2020-08-13 10:21 UTC by chinmayic

2020-08-27 10:48 UTC, ashraf-vazeer requested changes
Please address the comment

2020-08-27 10:48 UTC, ashraf-vazeer commented on docs/index.html
Can you check if there is version with ODIM folder?
that is,  ODIM_v1.0 or it should be just ODIM?

2020-09-02 07:33 UTC, ashraf-vazeer approved these changes
Look good to me

2020-09-02 09:56 UTC, rahulroshan-kachchap approved these changes
LGTM

2020-09-03 16:09 UTC, merged