Issue 374: Fabric APIs with Schema 2020.3 are not working from ODIM
ODIM-Project/ODIM pull request #382
Opened 2021-02-04 05:04 UTC by a-ajith

The PR contains:
- Added new model for AddressPool to lib-dmtf
- Modifying existing AdderssPool implementation in svc-fabrics to work along with fabric plugin
- Added TODO messages indicating that the models in svc-fabrics will be soon replaced with the lib-dmtf once fabric plugin is ready.

closes #374

2021-02-04 05:07 UTC, bharath-b-hpe approved these changes

2021-02-04 10:31 UTC, Bharath-KKB approved these changes

2021-02-04 15:59 UTC, Bharath-KKB requested changes
update tags

2021-02-05 07:30 UTC, Bharath-KKB approved these changes

2021-02-05 07:30 UTC, merged