Development
ODIM-Project/ODIM pull request #716
Opened 2021-12-12 18:36 UTC by divya-nettem

Redfish composition service implementation.

2022-01-10 11:02 UTC, amar-shalgar requested changes
Please address comments

2022-01-11 11:30 UTC, shivacharanms requested changes
The initial set of comments.

2022-01-11 11:30 UTC, shivacharanms commented on install/Docker/dockerfiles/scripts/build_odim.sh
> +    if [[ "$i" == "svc-composition-service" ]]; then
The if condition can be removed as there is no change to 'Dockerfile.odim' and svc-composition-service will not be listed here.

2022-01-11 11:30 UTC, shivacharanms commented on install/Docker/dockerfiles/scripts/start_composition_service.sh
> +	nohup /bin/svc-composition-service --registry=etcd --registry_address=${registry_address} --server_address=csplugin:45100 --client_request_timeout=`expr $(cat $CONFIG_FILE_PATH | grep SouthBoundRequ
Port 45100 is assigned to a different service, please use the next available port in the preferred series to maintain uniformity. 
Suggested port: 45112

2022-01-11 11:30 UTC, shivacharanms commented on install/Docker/dockerfiles/scripts/start_composition_service.sh
> +	nohup /bin/add-hosts -file /tmp/host.append >> /var/log/csplugin_logs/csplugin.log 2>&1 &
As mentioned above, cs is a service and not a plugin. Please make the changes accordingly.

2022-01-11 11:30 UTC, shivacharanms commented on lib-utilities/proto/compositionservice/composition_service.pb.go
> +// Code generated by protoc-gen-go. DO NOT EDIT.
Headsup: The *pb.go files will be no longer be part of the github repo as these are generated on the go.

2022-01-11 11:30 UTC, shivacharanms commented on lib-utilities/proto/compositionservice/composition_service.proto
> +}
Indentation to be handled across the file

2022-01-11 11:30 UTC, shivacharanms commented on lib-utilities/services/rpcService.go
> +			log.Infof("In GetEnabledServiceList Composition service")
Log to be removed/ Modified to a better debug log.

2022-01-11 11:30 UTC, shivacharanms commented on odim-controller/helmcharts/csplugin/csplugin-config.yaml
> +csplugin:
Content under helmcharts should be changed to reflect how a service is deployed, looks like these are in line with a plugin. Please compare any odim service and make the changes accordingly.

2022-01-11 11:30 UTC, shivacharanms commented on svc-api/models/serviceroot.go
> +	CompositionService        *Service     `json:"CompositionService"`
'omitempty' needs to added, please refer above lines of code.

2022-01-12 11:25 UTC, shivacharanms requested changes
Please address the review comments.

2022-01-12 11:25 UTC, shivacharanms commented on svc-composition-service/app/config/config.py
> +CONF_FILE = os.getenv("PLUGIN_CONFIG_FILE_PATH")
As mentioned above, please modify your logic to see composition service as a service and not a plugin.
Use service config file, which does not need odim credentials, ideally, service would need certificates for rpc communication and DB details.

2022-01-12 11:25 UTC, shivacharanms commented on svc-composition-service/app/config/constants.py
> +EVENT_DESTINATION_URL = "/redfish/v1/EventService/CompositionServiceEvent"
Refrain from using 'redfish/v1' for destination URI's

2022-01-12 11:25 UTC, shivacharanms commented on svc-composition-service/app/config/constants.py
> +EVENT_SUBSCRIPTION_URL = "/redfish/v1/EventService/Subscriptions"
Why declare event service api when an RPC call can be made?

2022-01-12 11:25 UTC, shivacharanms commented on svc-composition-service/app/config/constants.py
> +SYSTEMS_URL = "/redfish/v1/Systems"
Why declare systems service api when an RPC call can be made?

2022-01-12 11:25 UTC, shivacharanms commented on svc-composition-service/app/config/constants.py
> +    "Id": "1",
Make sure this value is compliant with redifsh spec.

2022-01-12 11:25 UTC, shivacharanms commented on svc-composition-service/app/config/constants.py
> +    "Id": "ComputerSystemBlock",
Make sure this value is compliant with redifsh spec.

2022-01-12 11:25 UTC, shivacharanms commented on install/Docker/dockerfiles/scripts/start_composition_service.sh
> +	nohup /bin/svc-composition-service --registry=etcd --registry_address=${registry_address} --server_address=csplugin:45100 --client_request_timeout=`expr $(cat $CONFIG_FILE_PATH | grep SouthBoundRequ
Also the composition service should be part of odimra logs, please refer other service start script file to get the path

2022-01-12 11:25 UTC, shivacharanms commented on svc-composition-service/app/db/persistant.py
> +            logging.error(
Please make sure the logs are redirected to the log file defined in the start script.

2022-01-12 11:25 UTC, shivacharanms commented on svc-composition-service/app/proto/composition_service.proto
> +syntax = "proto3";
Please explain the reasoning behind having the proto file under the composition service. Which is an exact match of the file present under lib-utilities.

2022-01-12 11:25 UTC, shivacharanms commented on svc-composition-service/app/rest/resource_zones.py
> +            # request_data = {
Remove commented code

2022-01-14 05:57 UTC, amar-shalgar requested changes
Please address comments

2022-01-14 05:57 UTC, amar-shalgar commented on install/Docker/dockerfiles/Dockerfile.compositionService
> +FROM ubuntu:18.04
Please use Ubuntu 20.04

2022-03-04 13:25 UTC, divya-nettem commented
Raised another pull request. So closing this obsolete pull request.

2022-03-04 13:25 UTC, closed without merging