odim-5495: Add go.mod file in scripts folder
ODIM-Project/ODIM pull request #745
Opened 2022-01-27 06:24 UTC by hemkapoor

Add go.mod file in scripts folder

2022-01-27 10:23 UTC, shivacharanms approved these changes

2022-01-28 07:53 UTC, jeevan-kamkar approved these changes

2022-01-28 07:54 UTC, shivacharanms requested changes

2022-01-28 07:54 UTC, shivacharanms commented on odim-controller/scripts/go.mod
> +module odim-5334/ODIM/odim-controller/scripts
Path need to be changed, it should not include reference to specific branch

2022-01-31 02:58 UTC, shivacharanms approved these changes

2022-01-31 03:03 UTC, merged