Bruce 6339: bug fix
ODIM-Project/ODIM pull request #956
Opened 2022-07-26 13:32 UTC by Shahid097

2022-07-26 13:54 UTC, amar-shalgar requested changes

2022-07-26 13:54 UTC, amar-shalgar commented on svc-managers/mgrresponse/managers.go
> +	OdataType       string      `json:"@odata.type,omitempty"`
@odata.type is a required property, this should not be omitempty

2022-07-26 13:54 UTC, amar-shalgar commented on svc-telemetry/tlresponse/list.go
> +	OdataType    string      `json:"@odata.type,omitempty"`
@odata.type is a required property, this should not be omitempty

2022-07-26 14:17 UTC, amar-shalgar commented
Please give a proper title to the PR

2022-07-27 08:34 UTC, amar-shalgar approved these changes

2022-07-27 08:34 UTC, shivacharanms approved these changes

2022-07-27 08:35 UTC, merged