Odim 6282
ODIM-Project/ODIM pull request #969
Opened 2022-08-04 04:34 UTC by AngithCJ

**Changes**
-  System is removed from aggregates if the system is deleted from ODIM
- unit test added
- bugfix : Removing one element from an aggregate ends up removing all element (BRUCE-6451)

2022-08-04 07:31 UTC, amar-shalgar requested changes

2022-08-04 07:31 UTC, amar-shalgar commented on svc-aggregation/system/deleteaggregationsource.go
write comments

2022-08-04 08:42 UTC, AngithCJ commented on svc-aggregation/system/deleteaggregationsource.go
added

2022-08-04 08:44 UTC, amar-shalgar approved these changes

2022-08-04 14:02 UTC, shivacharanms approved these changes

2022-08-05 04:24 UTC, jeevan-kamkar approved these changes

2022-08-05 11:59 UTC, merged