Sprint-58-odim-5943: Added new routes for PCIeFunctions
ODIM-Project/ODIM pull request #981
Opened 2022-08-11 16:51 UTC by sriteja-sabbineni

Issue: Service Validator (2021.2-Schema)- /redfish/v1/Chassis/6e7158df-ccf4-41c8-bb99-79cbc66a0bad.1/PCIeDevices is giving 404 response.
Added new routes for PCIeFunctions to fix this

2022-08-12 04:15 UTC, jeevan-kamkar approved these changes

2022-08-16 04:18 UTC, amar-shalgar requested changes

2022-08-16 04:18 UTC, amar-shalgar commented on svc-api/handle/handlers_test.go
> +	e.POST("/redfish/v1/Chassis/" + chassisID + "/PCIeDevices/" + rID + "/PCIeFunctions").Expect().Status(http.StatusMethodNotAllowed)
Normally we check methods only for the supported ones and all unsupported will be used with "Any"

2022-08-16 16:26 UTC, amar-shalgar approved these changes

2022-08-16 17:11 UTC, shivacharanms approved these changes

2022-08-16 19:22 UTC, merged